### ISSUE TITLE
#5 Create trailblazer operation & contract to create user

### ISSUE THREAD

**Issue by panSarin** [2N-IT/it-reviews-trb#5]
1. Write tests that will cover those cases:
  * valid data:
    - user was created & result is success
    - email with confirmation link was sent
  * invalid data ( email / password is blank or nil )
    - user was not created & result is failure
    - none email was sent
2. Implement operation & contract which will make above tests to pass

**Comment by PyrinAndrii** [comment]
should we use ActionMailer for this issue?

**Comment by KamilMilewski** [comment]
@PyrinAndrii yep

**Comment by krzykamil** [comment]
Done in https://github.com/2N-IT/it-reviews-trb/pull/8/files 
Grea job @PyrinAndrii !
