### ISSUE TITLE
#7 Add rubocop gem to project

### ISSUE THREAD

**Issue by panSarin** [2N-IT/it-reviews-trb#9]
Each project should have its linter rules and linter tool that will ensure the team to stick to those rules.

**Comment by panSarin** [comment]
@KamilMilewski please add rules that you think we should add to default rubocop configuration.

**Comment by PyrinAndrii** [comment]
Do we need only 'rubocop', or we should add, for example: 'rubocop-performance',  'rubocop-rails',  'rubocop-rspec' as well?

**Comment by krzykamil** [comment]
Yea go ahead and add the ones you mentioned, the new prefered way they (rubocop people) have is a modular approach with smaller gems/

**Comment by krzykamil** [comment]
https://github.com/2N-IT/it-reviews-trb/pull/13
